name = "gst-ecom-ez"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist/public"

[[d1_databases]]
binding = "DB"
database_name = "gst-ecom-ez-db"
database_id = "2734a637-4769-45c9-b5ae-e4c51c94fd37"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "gst-ecom-ez-storage"

[vars]
ENCRYPTION_KEY = ""
